# This workflow will build and push a new container image to Docker Hub,
# and then will deploy a new task definition toMinikube Cluster Via terraform. when there is a push to the "main" branch.


name: Deploy to Docker-Hub
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.CI_REGISTRY_USER}}
        password: ${{secrets.CI_REGISTRY_PASSWORD}}

    - name: Print Debug Info
      run: |
        echo "repo=${{vars.CI_REGISTRY}}:${{vars.DOCKER_TAG}}"
        pwd
        ls -la

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ${{secrets.CI_REGISTRY_USER}}/${{vars.CI_REGISTRY_IMAGE}}:${{vars.DOCKER_TAG}}
        file: ./backend/Dockerfile
